Repository supriya46788/BakeGenuis-AI, pull requests merged in 2025-08, with the labels that each got.

#65 add contact page and follow links
  css/about.css
  css/contact.css
  html/about.html
  html/contact.html
Labels: good first issue, GSSoC25, Level 1

#188 Big Fix : Contributor details fixed , private keys removed to prevent security issues
  css/about.css
  js/about.js
Labels: bug, GSSoC25, Level 3

#232 Feature/toast notifications updated
  css/toast.css
  html/login.html
  html/signup.html
  index.html
  js/auth.js
Labels: enhancement, GSSoC25, Level 3
